name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Install npm packages
        run: |
           cd functions
           npm install
  deploy:
     name:  Deploy to Firebase
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Go to Functions folder
         run: |
          cd functions
          ll
         
       - name: Start deploy
         uses: w9jds/firebase-action@master
         with:
          args: deploy --only functions
         env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
